### ISSUE TITLE
render_junocam_cube.py segfault on 2nd glClear call

### ISSUE THREAD

**Issue by BrianSwift** [kmgill/cassini_processing#1]
render_junocam_cube.py segfaults on 2nd call to glClear on line 249.

Environment: MacOS 10.13.6 running as guest under VMWare Fusion 10.1.3. Guest configured with 4 Cores and 6 GB RAM.
Python 2.7 in Anaconda environment with additions of
```
pip install libtiff
pip install pvl
pip install utm
pip install pyopengl
pip install spiceypy
pip install PyOpenGL_accelerate
```

Steps to reproduce in debugger:
```
 python -m pdb ../cassini_processing/render_junocam_cube.py -k /isiswork/isis3/data -r JNCE_2017350_10C00027_V01_RED_Mosaic.cub -g JNCE_2017350_10C00027_V01_GREEN_Mosaic.cub -b JNCE_2017350_10C00027_V01_BLUE_Mosaic.cub -l JNCE_2017350_10C00027_V01-raw-adjusted.lbl -o JNCE_2017350_10C00027_V01_Rendered_RGB.tif -W 3000 -H 3000
> /Volumes/VMware Shared Folders/vmSharedDl/isiswork/cassini_processing/render_junocam_cube.py(3)<module>()
-> import os
(Pdb) b 249
Breakpoint 1 at /Volumes/VMware Shared Folders/vmSharedDl/isiswork/cassini_processing/render_junocam_cube.py:249
(Pdb) c
Rendering Red...
> /Volumes/VMware Shared Folders/vmSharedDl/isiswork/cassini_processing/render_junocam_cube.py(249)render()
-> glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
(Pdb) c
Loading texture ' ./work/JNCE_2017350_10C00027_V01_RED_Mosaic.tif ... Done
Rendering Red...
> /Volumes/VMware Shared Folders/vmSharedDl/isiswork/cassini_processing/render_junocam_cube.py(249)render()
-> glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
(Pdb) s
Segmentation fault: 11
```

System generated traceback (probably not too useful)
[kevinRenderTraceback.txt](https://github.com/kmgill/cassini_processing/files/2380923/kevinRenderTraceback.txt)

**Comment by kmgill** [comment]
Can reproduce this issue, though it doesn't segfault on my system (I knew about this but thought it low priority). 

Throwing a GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT error if checking with glCheckFramebufferStatus

**Comment by kmgill** [comment]
Appears that glFramebufferTexture in Engine.display_for_export() is binding against the wrong texture id. Surprised it didn't blow up there, actually. Will provide fix shortly

**Comment by kmgill** [comment]
Applied a fix for the incorrect binding. Cleaned up some other stuff in render_junocam_cube.py while I was at it. Please verify this no longer segfaults.

**Comment by BrianSwift** [comment]
Verified I had the current  render_junocam_cube.py, retested with pdb, seeing same behavior, segfault on 2nd call to glClear (now at line 254.)

**Comment by kmgill** [comment]
Is this happening right as the program starts up or after you've pressed any keys? The bug fixed was effecting my system after I pressed 'p' to render the RGB image

**Comment by BrianSwift** [comment]
Before any key press, even before a window has appeared.

**Comment by kmgill** [comment]
Can you try running it directly without the python debugger (without `python -m pdb`).

Also, first script initcass.sh as

`. /path/to/initcass.sh`
`render_junocam_cube.py <options>`


I made a change where as long as initcass.sh contains the proper paths, you shouldn't need the -k option for render_junocam_cube.

Also, check and see if hardware acceleration is enabled for the virtual machine.

I expect you'll still get the segfault, but I want to just eliminate this possibility.

**Comment by kmgill** [comment]
Also, if possible, see if you can run any other OpenGL programs, just to see if it's my code or the underlying system

**Comment by BrianSwift** [comment]
```
time python ../cassini_processing/render_junocam_cube.py -r JNCE_2017350_10C00027_V01_RED_Mosaic.cub -g JNCE_2017350_10C00027_V01_GREEN_Mosaic.cub -b JNCE_2017350_10C00027_V01_BLUE_Mosaic.cub -l JNCE_2017350_10C00027_V01-raw-adjusted.lbl -o JNCE_2017350_10C00027_V01_Rendered_RGB.tif -W 3000 -H 3000
Rendering Grayscale frame with red channel...
Loading texture ' ./work/JNCE_2017350_10C00027_V01_RED_Mosaic.tif ... Done
Rendering Grayscale frame with red channel...
Segmentation fault: 11
```

**Comment by BrianSwift** [comment]
I was able to run some of the pyopengl demos.

**Comment by BrianSwift** [comment]
For what it's worth, here is the output of `python gears.py -info` from `PyOpenGL-Demo-3.0.1a1/PyOpenGL-Demo/GLUT` which shows info about my OpenGL environment.

GL_RENDERER   =  Apple Software Renderer
GL_VERSION    =  2.1 APPLE-16.7.4
GL_VENDOR     =  Apple Inc.
GL_EXTENSIONS =  GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod 
285 frames in 5.0 seconds = 56.966 FPS
275 frames in 5.0 seconds = 54.827 FPS
300 frames in 5.0 seconds = 59.980 FPS
301 frames in 5.0 seconds = 60.021 FPS

**Comment by BrianSwift** [comment]
It is working now!
This is after I updated the "VMWare Tools" in the guest environment.
The segfault may be related to having a small virtual display size, which was my case before the update. After the update I had a large display size and it worked. When I reduced the displays size, I got the segfault again.

**Comment by kmgill** [comment]
Ok, glad it's working. And I fixed an apparently unrelated bug that needed fixing, too :-)

I'll try to test against a small display size. It has a default size, which may be too big for the smaller displays. I'll try to reproduce the error

**Comment by kmgill** [comment]
render_junocam_cube.py has been deprecated in favor of junocam_create_model.py/process_junocam.py and the use of Blender for rendering.
